### PR TITLE
added user input field 'Sort Title' and corresponding client-side backend code

### PR DESCRIPTION
**Pull request by sentrywasbored**
Client-side update for early-access metadata/game details system adding Sort Title and it's corresponding backend to the client. Ready for push if/when server-side db is ready to accept entries for sort_title

### CODE REVIEW

**Review by Yelo420 — COMMENTED** [review]
Looks good. Will merge, after serverside changes are finished.

**Comment by Alfagun74** [comment]
There is one thing missig. You need to use the "sort_title" in the URL instead of the "title" now when building the search query parameters in the library.

**Comment by Yelo420** [comment]
You mean modify the library filter value dictionary from:
```
var dict = new Dictionary<string, string>
                {
                    {"Title","title"},
                    {"Size","size" },
```
to
```
var dict = new Dictionary<string, string>
                {
                    {"Title","sort_title"},
                    {"Size","size" },
```

**Comment by Alfagun74** [comment]
@Yelo420 yeah and if you have a free minute go ahead do it for him and merge it :) Because its all ready backend wise and i cant wait to try it on our own server.

**Comment by sentrywasbored** [comment]
> There is one thing missing. You need to use the "sort_title" in the URL instead of the "title" now when building the search query parameters in the library.

I caught this last night but I was too tired to commit the changes lol

**Pull request merged**
